FROM postgres

# Скопируйте ваши сертификаты в контейнер
COPY ./certs/server.crt /var/lib/postgresql/certs/server.crt
COPY ./certs/server.key /var/lib/postgresql/certs/server.key
COPY ./certs/rootCA.crt /var/lib/postgresql/certs/rootCA.crt

# Установите правильные права на файлы
RUN chown postgres:postgres /var/lib/postgresql/certs/server.crt /var/lib/postgresql/certs/server.key /var/lib/postgresql/certs/rootCA.crt && \
    chmod 600 /var/lib/postgresql/certs/server.key && \
    chmod 600 /var/lib/postgresql/certs/server.crt && \
    chmod 600 /var/lib/postgresql/certs/rootCA.crt
