# Определение версии Docker Compose и начало описания сервисов
version: '3'

services:
  app:
    build: .
    container_name: botdev
    restart: always
    depends_on:
      - pgdb

  pgdb:
    # Использование готового образа postgres
    image: postgres
    # Задание переменных окружения для контейнера с postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
     # Задание имени контейнера для сервиса pgdb
    ports:
      - "5432:5432"
    container_name: pgdb
     # Связывание тома с директорией в контейнере для сохранения данных postgres
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
      - ./certs:/var/lib/postgresql/certs
    command: >
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/certs/server.crt
      -c ssl_key_file/var/lib/postgresql/certs/server.key
      -c ssl_ca_file=/var/lib/postgresql/certs/rootCA.crt

volumes:
  pgdbdata: null
