FROM postgres

# Создаём директорию для сертификатов и задаём права
RUN mkdir -p /var/lib/postgresql/certs && chown -R postgres:postgres /var/lib/postgresql/certs

# Копируем сертификаты
COPY ./certs/server.crt /var/lib/postgresql/certs/server.crt
COPY ./certs/server.key /var/lib/postgresql/certs/server.key
COPY ./certs/rootCA.crt /var/lib/postgresql/certs/rootCA.crt

# Устанавливаем права на сертификаты
RUN chown postgres:postgres /var/lib/postgresql/certs/server.crt /var/lib/postgresql/certs/server.key /var/lib/postgresql/certs/rootCA.crt && \
    chmod 600 /var/lib/postgresql/certs/server.key && \
    chmod 644 /var/lib/postgresql/certs/server.crt /var/lib/postgresql/certs/rootCA.crt

# Используем стандартный entrypoint PostgreSQL
CMD ["postgres"]
