# Определение версии Docker Compose и начало описания сервисов
version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.botdev
    container_name: botdev
    restart: always
    depends_on:
      - pgdb
      - pgadmin

  pgdb:
    build:
      context: .
      dockerfile: Dockerfile.pgdb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    command: >
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/certs/server.crt
      -c ssl_key_file=/var/lib/postgresql/certs/server.key
      -c ssl_ca_file=/var/lib/postgresql/certs/rootCA.crt
    init: true
    entrypoint: >
      bash -c "
      ls -l /var/lib/postgresql/certs &&
      docker-entrypoint.sh postgres"


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@test.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "5050:80"
    depends_on:
      - pgdb
    volumes:
      - pgadmindata:/var/lib/pgadmin
    restart: always

volumes:
  pgdbdata: null
  pgadmindata: null
