version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.botdev
    container_name: botdev
    restart: always
    depends_on:
      - pgdb
      - pgadmin
    networks:
      my_network:
        ipv4_address: 172.18.0.3

  pgdb:
    build:
      context: .
      dockerfile: Dockerfile.pgdb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"  # Откроет порт только внутри сети Docker
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    command: >
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/certs/server.crt
      -c ssl_key_file=/var/lib/postgresql/certs/server.key
      -c ssl_ca_file=/var/lib/postgresql/certs/rootCA.crt
    init: true
    entrypoint: >
      bash -c "
      ls -l /var/lib/postgresql/certs &&
      docker-entrypoint.sh postgres"
    networks:
      my_network:
        ipv4_address: 172.18.0.4

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@test.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "5050:80"
    depends_on:
      - pgdb
    volumes:
      - pgadmindata:/var/lib/pgadmin
    restart: always
    networks:
      my_network:
        ipv4_address: 172.18.0.5

volumes:
  pgdbdata: null
  pgadmindata: null

networks:
  my_network:
    ipam:
      config:
        - subnet: 172.18.0.0/16
